source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target "RecordLife" do
use_frameworks!
pod 'SnapKit', '~> 3.0.2'

#pod 'SQLite.swift', '~> 0.11.1'   #数据库
pod 'FMDB'
#pod 'RealmSwift'


#pod 'YYKit', '~> 1.0.9'
pod 'SwifterSwift', '~> 1.3.7'


pod 'IQKeyboardManager', '~> 4.0.7'



#pod 'ReactiveCocoa', '~> 5.0.0-alpha.6'
pod 'RxSwift', '~> 3.0'
pod 'RxCocoa', '~> 3.0'
pod 'RxDataSources'



pod 'Alamofire', '~> 4.2.0'
pod 'SwiftyJSON', '~> 3.1.3'


#s.osx.pod_target_xcconfig = {
#    'PUBLIC_HEADERS_FOLDER_PATH' => '$(WRAPPER_NAME)/Headers',
#    'PRIVATE_HEADERS_FOLDER_PATH' => '$(WRAPPER_NAME)/PrivateHeaders'
#}


#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
##            config.build_settings['ENABLE_BITCODE'] = 'NO'
#            config.build_settings['SWIFT_VERSION'] = '3.0'      # swift 2.3 or '2.3'
#        end
#    end
#end

#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '2.3' # or '3.0'
#        end
#    end
#end



#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        phase_name = 'Headers'
#        target.build_phases.each do |phase|
#            if (phase.display_name.include? phase_name)
#                target.build_phases.unshift(phase).uniq! unless target.build_phases.first == phase
#            end
#        end
#    end
#end

end
